[git_commit]
tag_disabled = false

[directory]
truncation_length = 4
truncate_to_repo = false

[ruby]
detect_variables = []

[kubernetes]
disabled = false

[gcloud]
format = 'on [$symbol$project]($style) '
